modLoader="javafml" #mandatory

loaderVersion="[27,)" #mandatory

issueTrackerURL="https://github.com/Shadows-of-Fire/EnderBags/issues" #optional

displayURL="https://minecraft.curseforge.com/projects/ignition-enderbags" #optional

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="ender_bags" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Ender Bags" #mandatory

description='''
Large colored bags, nothing more.
'''

[[dependencies.ender_bags]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
[[dependencies.ender_bags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.attained_drops]]
    modId="placebo"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"